#!/bin/sh

#run_hook() {
run_latehook() {

	#find mounted root by grepping current mount points with <root>
	mount | cut -d ' ' -f 3 | grep root || return 1
	local __root="$(mount | cut -d ' ' -f 3 | grep root | tail -1)"
	##launch_interactive_shell	#proper subshell invoke... to experiment

	trap 'set +ex; launch_interactive_shell' EXIT
	set -ex

	echo "Found root device: at $__root, moving mount"
       	mkdir /oldroot
       	mount --move $__root /oldroot

	echo "Setting up RAM root..."
	mount -t tmpfs tmpfs $__root -o size=95%

	echo "extracting from ramroot"
	cd $__root
	/bin/tarr xf /oldroot/ARCH.txz
	cd /

	echo "unmounting oldroot"
	umount /oldroot

	set +e

    	trap '' EXIT
}
